- src/components/editIcon/index.js
- src/components/editIcon/style.css
> 16 edit icon component

- src/components/editIcon/index.js
- src/components/post/index.js
https://trello.com/c/CYukrnnZ/54-update-all-hard-coded-edit-icons
> 19 change all hard coded edit icons

- src/context/auth.js
https://trello.com/c/m8iKMjJo/60-fix-login-bug
> fix login bug

- src/components/posts/index.js
- src/pages/dashboard/index.js
https://trello.com/c/uYQcr1AE/67-update-dashboard-so-new-posts-are-displayed-on-top
> Chloe-#46 dashboard fix posts render issue on new post submission

- src/components/myExercises/index.js
- src/components/myExercises/style.css
https://trello.com/c/cvDISOhg/69-my-cohort-page-myexercises-component
> add MyExercises Component

- src/context/auth.js
- src/pages/login/index.js
https://trello.com/c/AFQilHx7/21-client-login-form
> 23 user login form

- src/App.css
- src/components/header/style.css
- src/components/menu/menu.css
- src/components/navigation/style.css
- src/pages/dashboard/style.css
Trello ticket: https://trello.com/c/PW24e7kj/75-dashboard-fix-the-scroll-behaviour
> Nazar tymiv 56 dashboard fix the scroll behaviour

- src/components/myTeachers/index.js
- src/components/myTeachers/style.css
https://trello.com/c/h3PKOV6N/78-my-cohort-page-teachers-component
> add MyTeachers component

- .prettierrc
- src/components/editPostModal/index.js
- src/components/editPostModal/style.css
- src/components/modal/index.js
- src/components/modal/style.css
- src/components/modal/style.js
- src/context/auth.js
- src/pages/dashboard/index.js
Trello link: https://trello.com/c/xS2V4GPW/85-fix-styles-for-edit-modal-window-of-post-component
> Nazar tymiv 77 update post settings styles

- src/components/myCohortDetails/index.js
- src/components/myCohortDetails/style.css
https://trello.com/c/38EQ7t7v/22-student-view-add-mycohortdetails
> add MyCohortDetails component

- src/context/auth.js
https://trello.com/c/TaLGGXoa/96-login-sign-up-toggle-button-issue
> fix toggle login/sign up button

- src/components/ProfileContextMenu/index.js
- src/components/ProfileContextMenu/style.css
- src/components/userCard/index.js
https://trello.com/c/yPjedbhf/80-profilecontextmenu-remove-route-and-update-css
- updated CSS for better positioning
- removed useNavigate and routes until they are built.
> 92 profilecontextmenu remove route update css

- src/components/ProfileContextMenu/style.css
BUG FIX: z-index on wrong class.
> FIX: z-index issue.

- src/service/apiClient.js
I mean i put the functions back and exported them, but compiling isn't possible due to compiling issues relating to internationalization
> put toggleLike and postComment back

- src/components/CommentsList/index.js
- src/components/post/index.js
- src/service/apiClient.js
Trello ticket: https://trello.com/c/POla4M4K/120-dashboard-comments-visibility-can-be-toggled
> Comments visibility

- src/App.js
- src/pages/cohorts/index.js
https://trello.com/c/vyge7UiZ/151-teacher-view-cohorts-page-add-new-route-cohorts
> add: create the route for teacher view 

- src/components/CommentsList/index.js
- src/components/commentInput/index.js
- src/components/post/index.js
Trello ticket: https://trello.com/c/0ZLnNRk2/161-refresh-all-comments-when-add-new-one
> Move comment input into comments list

- src/service/apiClient.js
https://trello.com/c/dh4IXgkK/193-add-getstudentsbycohortid-to-apiclient
> add getStudentsByCohortId

- src/service/apiClient.js
Made a mistake with a colon. Not sure how it got passed my senior dev.....
> REMOVE: colon

- src/components/myCohortDetails/index.js
- src/components/myCohortTeachers/index.js
- src/pages/myCohort/index.js
https://trello.com/c/IcL4PbVz/152-student-view-my-cohort-page-fix-displayed-users-bug
> Student view: my-cohort page: fix displayed students bug

- Teamdevclient-workspace.code-workspace
- src/components/post/index.js
- src/context/auth.js
Trello ticket: https://trello.com/c/eoJL8me2/146-dashboard-teacher-view-can-delete-any-post
> Teacher can delete any post

- src/service/apiClient.js
https://trello.com/c/DjZUcRBm/199-apiclient-update-patch-to-put
> patch to put updated

- src/pages/dashboard/index.js
Trello ticket: https://trello.com/c/esMnBSts/210-dashboard-student-vs-teacher-view-conditional-rendering-relies-on-auth-context-data
> Student VS teacher view

- src/components/myCohortTeachers/index.js
https://trello.com/c/6ZvuVTJf/213-student-view-my-cohort-page-update-myteachers-component
> update UserCard user prop for myCohortTeachers component
